name: Android CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew build
